export { default as CreateAdvert } from './CreateAdvert.vue'
export { default as CreateStore } from './CreateStore.vue'
export { default as CropImage } from './CropImage.vue'
export { default as Login } from './Login.vue'
export { default as SignUp } from './SignUp.vue'